services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared-network
    depends_on:
      - authservice
      - borrowservice
      - reservationservice
      - inventoryservice
      - inventorydatabase

  authservice:
    build:
      context: ./services/auths
      dockerfile: Dockerfile
    env_file:
      - ./services/auths/.env
    networks:
      - shared-network

  borrowservice:
    build:
      context: ./services/borrow
      dockerfile: Dockerfile
    env_file:
      - ./services/borrow/.env
    networks:
      - shared-network

  reservationservice:
    build:
      context: ./services/reservation
      dockerfile: Dockerfile
    env_file:
      - ./services/reservation/.env
    networks:
      - shared-network

  inventoryservice:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run build && node dist/index.js"
    environment:
      NODE_ENV: development
    env_file:
      - ./services/inventory/.env
    networks:
      - shared-network
    depends_on:
      - inventorydatabase

  inventorydatabase:
    image: postgres:15
    restart: always
    env_file:
      - ./services/inventory/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  postgres_data:
